- name: configuring catalogue 
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nodejs -y 
    ansible.builtin.command: dnf module disable nodejs -y
    
  - name:  enable required nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs -y
    ansible.builtin.dnf:
      name:  nodejs 
      state: present
  - name: crete system user
    ansible.builtin.user:
     name: roboshop
     system: true
     shell: /sbin/nologin
     home: /app
  - name: create a app directory
    ansible.builtin.file:
     path: /app 
     state: directory

  - name: download the file
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
     dest: /tmp/catalogue.zip
     
  - name: extract the file
    ansible.builtin.unarchive: 
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  # -name: download the file 
  #  ansible.builtin.get_url:
  #    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
  #    dest: /tmp/catalogue.zip   
  # - name: extract the file
  #   ansible.builtin.unarchive:
  #    src: tmp/catalogue.zip
  #    dest: /app


