# - name: ansible facts
#   hosts: local
#   connection: local
#   tasks:
#    - name: facts
#      anisble.builtin.debug:
#       msg: " {{ anisble_facts }} "

- name: ansible facts
  hosts: local
  connection: local

  tasks:
    - name: facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
```
