
- name: ping the server
  hosts: local
  connection: local
  tasks: 
   - name: Print the helloworld
     ansible.builtin.debug:
      msg: "heloo doctor heart miss ayijndi"
    #  msg: "VYSHU, Good Morning!!!"