
- name: install nginx
  hosts: frontend
  tasks:
   - name: install inginx 
     ansible.builtin.package:
      name: nginx
      state: present

   - name: run the nginx
     ansible.builtin.service:
       name: nginx
       state: started  
       enabled: yes 
    