- name: install package
  hosts: frontend
  become: yes
  tasks:
  - name: packages installing
    ansible.builtin.debug:
     name: " {{ item.name }} "
     name: "{{ item.state }}"
    loop: 
    - {name: 'nginx',state: 'present'}
    - {name: 'mysql', state:'present'}