
[frontend]
13.221.116.172  username=Cherry password=9876 ansible_user=ec2-user ansible_password=DevOps321
98.84.142.100   username=vyshali password=234 ansible_user=ec2-user ansible_password=DevOps321

[local]
localhost