
- name: var_files
  hosts: frontend
  
  # vars_files: 
  #  course.yaml
   

  tasks:
  - name: trainer  info
    ansible.builtin.debug:
     msg: " Trainer details is {{ username }} and age is {{ password }}" 

  #  - name: trainer  info
  #   ansible.builtin.debug:
  #    msg: " Trainer details is {{ Trainer }} and age is {{ AGE }}" 