
-  name:  VARIABLES
   hosts: local
   connection: local

   vars:
     COURSE: JAVA
     Name: VYSHNAVI

   tasks:
    - name: course details
      ansible.builtin.debug:
        msg: "hello {{ COURSE }}, baggunnava {{ Name }}"

    - name: trainer
      ansible.builtin.debug:
       msg: " Tranier name is {{ Name }}"    
