
- name: ping the server
  hosts: local
  connection: local
  vars:
   COURSE: JAVA
   TIME: 30 minutes

  tasks: 
   - name: Print the helloworld
     ansible.builtin.debug:
      msg: "hello {{ COURSE }}"
    

# - name: ping the server
#   hosts: local
#   connection: local
#   tasks:
#   vars: 
#    COURSE: PYTHON 3

#    - name: Print the helloworld
#      ansible.builtin.debug:
#       msg: "hello {{ COURSE }} 3"